### ISSUE TITLE
libstdc++ is deprecated; move to libc++

### ISSUE THREAD

**Issue by Amcio** [andugu/Peeko#1]
When I do make I got this error:
`clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of iOS 7
ld: library not found for -ldylib1.o` 

How do I fix this?

**Comment by andugu** [comment]
This project has been discontinued, so don't expect it to work with new versions of Snapchat or theos. If you want a tweak like this, please use Phantom. But if you want to use this code for a new project or something, please add more details so I can help you better :)

**Comment by Amcio** [comment]
I didn't know it's discontinued. No one told me hah. I never thought of using it in Snapchat though. I must disappoint you, I don't work on a new project or something. Just wanted to bring 3d touch to my favorite apps on my SE without jailbreak.

**Comment by andugu** [comment]
To update the code to work with iOS 10 you should look at the original [code](https://github.com/andrewwiik/Tweaks/tree/master/peekaboo)
But also, the actual code should work even in iOS 10, the issue must be with your theos setup, so try following a tutorial or reinstalling/upgrading theos.

**Comment by Amcio** [comment]
Thanks I'm gonna try reinstalling theos.
